#!/bin/sh

if [ $# -lt 1 ]; then
    echo "Usage:"
    echo "  $(basename $0) <host:port>"
    exit 1
fi

trap 'echo got sigint' SIGINT

RCV_PORT=9999
HOST=$1

echo "-- starting pipeline ${PIPELINE}"

set -x
GST_DEBUG=3 gst-launch-1.0 udpsrc port=${RCV_PORT} \
         ! 'application/x-rtp,media=(string)video,clock-rate=(int)90000,encoding-name=(string)H264,payload=(int)96' \
         ! rtph264depay \
         ! avdec_h264 \
         ! videoconvert \
         ! xvimagesink &

set +x
pipeline_pid=$!
echo "-- pipeline started as ${pipeline_pid}"

echo "-- starting stream, stream host: ${HOST}"
ID=$(curl -X POST http://${HOST}/start?port=${RCV_PORT})
echo "-- got ID: $ID"

while true; do
    echo "-- keepalive ping"
    curl -X POST http://${HOST}/alive?id=${ID}
    sleep 30 || break
    echo $?
done

curl -X POST http://${HOST}/stop?id=${ID}

echo "-- stopping pipeline"
kill -9 $pipeline_pid 2>/dev/null


